Update snyk-code.yml

diff --git a/.github/workflows/snyk-code.yml b/.github/workflows/snyk-code.yml
--- a/.github/workflows/snyk-code.yml
+++ b/.github/workflows/snyk-code.yml
@@ -1,17 +1,36 @@
-name: "snyk code test"
-on: [push, pull_request]
-jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: snyk/actions/setup@master
-      - name: Snyk Test
-        run: snyk code test --org=${{ secrets.SNYK_ORG }} --sarif > snyk-sarif2.json
-        continue-on-error: true
-        env:
-           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-      - name: Upload SARIF file
-        uses: github/codeql-action/upload-sarif@v2
-        with:
-          sarif_file: snyk-sarif2.json
+name: Snyk SCA, Code, IaC and Container CLI monitor example
+	
+	on:
+	  push:
+	    branches: [ main ]
+	
+	jobs:
+	  build:
+	    name: Test and build
+	    environment: snyk-npm
+	    runs-on: ubuntu-latest
+	
+	    strategy:
+	      matrix:
+	        node-version: [16.x]
+	        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
+
+	    steps:
+	    - uses: actions/checkout@v2
+	    - name: Use Node.js ${{ matrix.node-version }}
+	      uses: actions/setup-node@v2
+	      with:
+	        node-version: ${{ matrix.node-version }}
+	        cache: 'npm'
+	        
+	    - name: Setup Snyk + snyk-to-html
+	      run: |
+	        npm install snyk -g
+	        npm install snyk-to-html -g
+	        snyk auth ${{secrets.SNYK_TOKEN}}
+	    - name: Snyk Open Source # For testing and failing please add snyk test before snyk cmonitor
+	      run: |
+	        snyk monitor
+	    - name: Snyk Code # Remove || true to fail if there are vulnerabilities
+	      run: |
+	        snyk code test || true 
